### ISSUE TITLE
1.0.9之前的版本 默认内置3种状态是可以重试回调，之后的版本因为enableReload默认false，请问如何开启内置样式的enableReload

### ISSUE THREAD

**Issue by ByteRax** [Zhao-Yan-Yan/MultiStatePage#13]
如题 不想重写内置样式 

大多数情况下内置样式已经可以满足了

**Comment by Zhao-Yan-Yan** [comment]
建议 自定义state

**Comment by ByteRax** [comment]
关于内置样式，我看MultiStateConfig可以配置动画时长、文案、图标，那么关于这个重试回调，是否也可以在这里配置呢，毕竟内置样式真的非常好用，对于大多数项目来说，能满足99%的需求

**Comment by Zhao-Yan-Yan** [comment]
想了一下确实没必要 最好还是自定义state 需求多变谁知道那一天改成啥样
