### ISSUE TITLE
如果对你有帮助的话可以点个star支持一下子哦

### ISSUE THREAD

**Issue by Zhao-Yan-Yan** [Zhao-Yan-Yan/MultiStatePage#2]

**Comment by xuezhimin** [comment]
好的呢，亲


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhao-Yan-Yan/MultiStatePage"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 下午4:01
收件人:&nbsp;"Zhao-Yan-Yan/MultiStatePage"<MultiStatePage@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhao-Yan-Yan/MultiStatePage] 如果对你有帮助的话可以点个star支持一下子哦 (#2)





 
Closed #2.

**Comment by Zhao-Yan-Yan** [comment]
> 好的呢，亲
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhao-Yan-Yan/MultiStatePage" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 下午4:01 收件人:&nbsp;"Zhao-Yan-Yan/MultiStatePage"<MultiStatePage@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [Zhao-Yan-Yan/MultiStatePage] 如果对你有帮助的话可以点个star支持一下子哦 (#2) Closed #2. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

西八
