### ISSUE TITLE
可以停止动画吗？

### ISSUE THREAD

**Issue by geziin** [Zhao-Yan-Yan/MultiStatePage#25]
作者大大你好，请问下在StateLoading里面用了自定义的动画，需要在哪里停止这个动画呢，目前showSuccess只是把StateLoading页面隐藏了，但是动画没停止，可以可以加个类似onMultiStateViewCreate的方法来监听页面隐藏了呢
![image](https://user-images.githubusercontent.com/88422082/232959593-e6c98ef7-8d4c-4058-8e16-d6b2e403a49a.png)

**Comment by geziin** [comment]
我是这样处理的，也可行
![image](https://user-images.githubusercontent.com/88422082/232961636-25edd556-ed4d-4a47-bd25-cb47e3dee66d.png)

**Comment by geziin** [comment]
我在自定义view里面这样处理的，试了下也可以
![image](https://user-images.githubusercontent.com/88422082/232961729-432beac4-394a-4f23-b252-ef0ba794ad05.png)

**Comment by Zhao-Yan-Yan** [comment]
这里确实可以优化下，你这样也是可以的 👍🏻
