### ISSUE TITLE
直接使用会报activity原来布局id空指针

### ISSUE THREAD

**Issue by crazyzjw** [Zhao-Yan-Yan/MultiStatePage#4]

**Comment by crazyzjw** [comment]
发现必须在设置控件监听或者赋值后才能show,否则会找不到布局的控件id

**Comment by Zhao-Yan-Yan** [comment]
@crazyzjw 没太懂 可以发一下代码

**Comment by crazyzjw** [comment]
kotlin里面我在oncreate里面show<Loading>之后代码设置textview文案或者设置点击事件会报异常说找不到那些控件id,去掉show就正常

**Comment by Zhao-Yan-Yan** [comment]
确实是这样的  现在的设计是 show其他state时会移除原view 所以才会找不到id

**Comment by Zhao-Yan-Yan** [comment]
目前的解决办法是 先 show SuceecssState 再去修改原view的内容

**Comment by Zhao-Yan-Yan** [comment]
@crazyzjw 1.0.6 已优化

**Comment by crazyzjw** [comment]
> @crazyzjw 1.0.6 已优化

好的,因为不这样的话,其实会很耦合逻辑

**Comment by Zhao-Yan-Yan** [comment]
嗯 是的
