### ISSUE TITLE
如何设置不遮盖自定义的标题栏

### ISSUE THREAD

**Issue by crazyzjw** [Zhao-Yan-Yan/MultiStatePage#5]
现在都是占满布局,如果想腾出空间给自己的标题栏要设置什么

**Comment by Zhao-Yan-Yan** [comment]
可以对某个 `view` 使用 `bindMultiState`

**Comment by crazyzjw** [comment]
> 可以对某个 `view` 使用 `bindMultiState`

..在activity不太好用吧
