### ISSUE TITLE
没有loading无隐藏状态

### ISSUE THREAD

**Issue by lzw-lost** [Zhao-Yan-Yan/MultiStatePage#6]
loading的时候应该有两种状态，隐藏布局（加载内容的时候），透明布局遮盖（提交接口的时候），代码中
![image](https://user-images.githubusercontent.com/5761796/100560403-a5cac000-32f0-11eb-9a98-1a70a35f01a5.png)会直接替换布局。

**Comment by Zhao-Yan-Yan** [comment]
这没什么问题吧

**Comment by Zhao-Yan-Yan** [comment]
没明白你的意思

**Comment by lzw-lost** [comment]
比如dialog那种把透明的页面，在调用接口的时候并不是完全替换布局，而是一层半透明的遮罩，对比lodsir的功能，自定义state的时候会有是否显示下方布局的回调

**Comment by Zhao-Yan-Yan** [comment]
我觉得这种 直接写dialog 更合适吧

**Comment by Zhao-Yan-Yan** [comment]
可以看看这个库https://github.com/kongzue/DialogX

**Comment by xiaolong125** [comment]
有问题，比如我上拉加载更多的时候要同时显示列表和loading，现在loading会把列表替换
