### ISSUE TITLE
当绑定的View为NestedScrollView时 showSuccess()无法展示布局 showEmpty()和showError()是没有问题的

### ISSUE THREAD

**Issue by NeVaDaAAA** [Zhao-Yan-Yan/MultiStatePage#7]
设备信息:小米 MIX 2S MIUI12开发版 20.9.4
Android 10

之前一直用的loadSir loadSir是没有问题的 作者可以测试一下

**Comment by Zhao-Yan-Yan** [comment]
NestedScrollView是不是在LinearLayout里 还加了权重   那一块是有点问题  我看看怎么弄一下

**Comment by Zhao-Yan-Yan** [comment]
1.0.8 修复了

**Comment by NeVaDaAAA** [comment]
> 1.0.8 修复了

为作者点赞 速度杠杠的
