### ISSUE TITLE
buildFail

### ISSUE THREAD

**Issue by gh7800** [Zhao-Yan-Yan/MultiStatePage#8]
Type com.zy.multistatepage.BuildConfig is defined multiple times: D:\XSHINEIOT\MultiStatePage\app\build\intermediates\project_dex_archive\debug\out\com\zy\multistatepage\BuildConfig.dex, D:\XSHINEIOT\MultiStatePage\app\build\intermediates\external_libs_dex\debug\mergeExtDexDebug\classes.dex

**Comment by Zhao-Yan-Yan** [comment]
你的as版本是多少 我4.1没啥问题

**Comment by gh7800** [comment]
原因:在多module的模式下,module的manifest 中的package有相同的,导致产生了两个相同的BuildConfig文件。
所以要更改module的清单文件

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxx.xxx">`

**Comment by Zhao-Yan-Yan** [comment]
还真是哈
